### ISSUE TITLE
readStream requires local temp file?

### ISSUE THREAD

**Issue by litp** [danhunsaker/flysystem-redis#1]
Very useful work. Just one question: I read the code and you use directly the trait `StreamedReadingTrait` in the adapter script file to implement the `readStream` method. The `StreamedReadingTrait` uses the `tmpfile()` function to open a temporary file. Does it mean this redis adapter still needs the reading and writting of local file system?
##

**Comment by danhunsaker** [comment]
That seems likely, yes.  Redis doesn't actually support streamed reading and writing, so we have to emulate it instead, which means storing the file contents temporarily in a way that _can_ be streamed.  This could probably be done in memory instead of on disk, and a PR that does this is more than welcome, but this approach may encounter issues with large files.

Any other ideas are also welcome!
